### ISSUE TITLE
openmpi 1.8.4 compile error on arm

### ISSUE THREAD

**Issue by opoplawski** [open-mpi/ompi-release#148]
Getting the following trying to build the Fedora package on arm:

psizeof_f.f90:17.21:
      COMPLEX(REAL128)::x
                     1
Error: Kind -1 not supported for type COMPLEX at (1)

Full log http://koji.fedoraproject.org/koji/getfile?taskID=8466599&name=build.log

I'm guessing the gen-mpi-sizeof.pl script is no running properly there for some reason.

**Comment by ggouaillardet** [comment]
@opoplawski 
could you please give a try to the patch available at https://gist.github.com/ggouaillardet/2e547e5505fb852af3f9

note that
- autotools are required (see http://www.open-mpi.org/source/building.php for the recommended versions) and libtool 2.4.3 is known to have problems with ompi
- i do not have an arm box, so all i can do is hope this patch is enough to build ompi on arm32 arch

based on your feedback, i will ask @jsquyres to review this and update both master and v1.8

**Comment by jsquyres** [comment]
@ggouaillardet thanks for the patch; it looks good.  I pushed it to master in open-mpi/ompi@cab1379dfbd63079defc26110b004e6c00e397d3.  

You did the hard work of making the patch, so I'll file the v1.8 PR.

**Comment by opoplawski** [comment]
Does appear to fix the issue.  Thanks.
