### ISSUE TITLE
release repo out of sync with main repo

### ISSUE THREAD

**Issue by marksantcroos** [open-mpi/ompi-release#167]
Hi,

I was trying to debug some Cray/ALPS related matters and noticed that the trivial fix (2a57e71a4778eb6d09256901c30cd2e0b5ba2760) which is already from May last year, is not in the release repo, let alone in the latest release.

I dont understand completely the purpose/policy of the two different repo's , but I cant imagine this diff is intentional.

Thanks

Mark

**Comment by jsquyres** [comment]
@hppritcha Can you check into this?

**Comment by hppritcha** [comment]
Yes I'll take a look.

**Comment by hppritcha** [comment]
@marksantcroos what's the alps problem?  That should probably be a separate issue.  Note we may have just decided not to push 2a57e71 back to the release branch.

**Comment by marksantcroos** [comment]
Well, the alps problem is a syntax error in the code if 2a57e71
<https://github.com/open-mpi/ompi-release/commit/2a57e71a4778eb6d09256901c30cd2e0b5ba2760>
is not pushed :-)
Note that there are many more commits that are in ompi and not in
ompi-release only by looking at the history of that single file.


Other than that, I'm just starting to get OpenMPI going on Hopper, a Cray
XE6.
I am now setting everything up to try with the latest version from git
(compiling as we speak).

**Comment by hppritcha** [comment]
@marksantcroos 
It would be better to use master for hopper (I use edison on a daily basis, I thought both machines are down now for maintenance this week).  I totally revamped how the configure/launch works for Cray systems to be more sane, but none of those changes went in to the release branch (1.8 branch).  

If you are doing work for end users then I guess we'll need to stick with 1.8.  I'm assuming you are not trying to use OMPI in CCM mode on hopper, correct?  

Oh and by master here I mean [open-mpi/opmi](https://github.com/open-mpi/ompi) work master.

I'll push 2a57e71 into 1.8.  But almost all the other commits I've been doing in orte/opal for Cray 
(including the big pmix rewrite that comes from the [pmix](https://github.com/open-mpi/pmix) work)
are not going to make it into the current release branch.  

We do plan to shortly branch master into the 1.9 release.  I'd be happy to work with you on
getting the 1.9 release into a production state on hopper.  Long range, I'm working on getting
OMPI prepared for the move to the cory and its sister KNL system at LANL.

**Comment by marksantcroos** [comment]
@hppritcha 
Indeed, master works for Hopper after same juggling with building and runtime configs.
Would be happy to learn your build/run config for Edison, as I'm just as happy to use Edison as Hopper to get going.

With "working" here I mean that I was able to run "normal" MPI applications compiled with OpenMPI, both through aprun and mpirun.

So my main interest in OpenMPI is that I want to work with Spawn() which is not available in Cray's implementation as you might be aware of. Do you have any experience with Spawn() on Cray and/or should I take this to the mailinglist? (I'm not subscribed yet)
Given your reference to pmix, I assume you have some familiarity with process management :-)

This is development work for which I'm currently the only user and therefore happy to use a version from git for the time being.

Thanks!

**Comment by rhc54** [comment]
OMPI supports comm_spawn on both master and 1.8 (and 1.6 for that matter). Last I checked, and I admit it has been a couple of years, it worked fine on Cray.

**Comment by hppritcha** [comment]
In theory, on hopper and edison, you should be able to use spawn functionality if you request a batch reservation that is larger than the initial job size launched via mpirun.  You do not get this
functionality using aprun though, using alps pdomain concept (which I don't think is
available on hopper till after the upgrade to CLE 5.2 - which I think is occurring this week), one
can do MPI comm connect/accept while using aprun.  This approach can work across separate
batch jobs.  We got this working for MPICH at a customer site which had a mapreduce style workload
but wanted to use mpi since the "mappers" and "reducers" were mpi apps themselves.

The key words above are "In theory".  

If you hit problems on hopper or edison open an issue on master and I'll work on it.

**Comment by marksantcroos** [comment]
Hmmm, interesting, that MR workload sounds similar to what I want to achieve!

Regarding your suggestions, I did that indeed, but that doesn't seem to make a difference.

So this might be one of the rare cases where theory and practice are not aligned ;-)

I created a ticket on the other repo, happy to close this one now.
