### ISSUE TITLE
hwloc_set_cpubind returned "Error" for bitmap

### ISSUE THREAD

**Issue by opoplawski** [open-mpi/ompi-release#223]
Running netcdf 4.3.3.1 test on armv7hl for Fedora builds with openmpi-1.8.4-134-g9ad2aa8.  Some test runs are aborting with:

Open MPI tried to bind a new process, but something went wrong.  The
process was killed without launching the target application.  Your job
will now abort.
  Local host:        arm02-builder06
  Application name:  ./tst_h_par
  Error message:     hwloc_set_cpubind returned "Error" for bitmap "0-3"
  Location:          odls_default_module.c:551

Also see:

WARNING: a request was made to bind a process. While the system
supports binding the process itself, at least one node does NOT
support binding memory to the process location.
  Node:  arm02-builder06
This usually is due to not having the required NUMA support installed
on the node. In some Linux distributions, the required support is
contained in the libnumactl and libnumactl-devel packages.
This is a warning only; your job will continue, though performance may be degraded.

**Comment by opoplawski** [comment]
The builder appears to have 4 cores.

**Comment by rhc54** [comment]
Hi Orion

Can you tell me what the command line looked like and/or any MCA params you
have set?

**Comment by opoplawski** [comment]
I'll see if I can get a definitive answer. For now it looks like:

mpiexec -n # ./tst_parallel4

With # = 1-4.  Not sure which # it failed on.  I'm guessing 1 at this point.  Unfortunately I cannot reproduce on my 1 core qemu VM.

**Comment by rhc54** [comment]
Question: is it possible that the other nodes in the hostfile or allocation
have the required binding support libs installed, but this one doesn't? I'm
trying to figure out why hwloc returned an error on that particular node -
it should have just done a "no-op" since we are binding to all the cores.

I'm also scratching my head over why we told it to do so unless you
somewhere said "bind-to none" - but then the bitmap should have been NULL
and that function call would be skipped.

**Comment by opoplawski** [comment]
This is a single node with no network access.  I wouldn't rule out arm7hl specific errors in hwloc as well.

**Comment by rhc54** [comment]
@bgoglin @jsquyres Guys - any ideas on the hwloc error?

**Comment by bgoglin** [comment]
No obvious idea. But we don't test hwloc on arm very often.
@opoplawski Assuming it's running Linux, can you send the tarball that hwloc-gather-topology creates on that node (you'll have to build hwloc) ?

**Comment by opoplawski** [comment]
Can you do with the output of lstopo-no-graphics -v?  It's very hard to get anything out of the builders.

**Comment by bgoglin** [comment]
Let's try that first, but set HWLOC_DEBUG_CHECK=1 in the environment before running this. And do lstopo-no-graphics -.xml for the full XML dump too.

**Comment by opoplawski** [comment]
Okay, I've confirmed the command line as:
~~~~~
+ mpiexec -n 1 ./tst_parallel4
--------------------------------------------------------------------------
WARNING: a request was made to bind a process. While the system
supports binding the process itself, at least one node does NOT
support binding memory to the process location.
  Node:  arm04-builder23
This usually is due to not having the required NUMA support installed
on the node. In some Linux distributions, the required support is
contained in the libnumactl and libnumactl-devel packages.
This is a warning only; your job will continue, though performance may be degraded.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Open MPI tried to bind a new process, but something went wrong.  The
process was killed without launching the target application.  Your job
will now abort.
  Local host:        arm04-builder23
  Application name:  ./tst_parallel4
  Error message:     hwloc_set_cpubind returned "Error" for bitmap "0-3"
  Location:          odls_default_module.c:551
--------------------------------------------------------------------------
~~~~~

lstopo output:

~~~~~~
Machine (P#0 local=4137128KB total=4137128KB HardwareName=Highbank HardwareRevision=0000 HardwareSerial=0000000000000000 Backend=Linux OSName=Linux OSRelease=3.19.1-201.fc21.armv7hl OSVersion="#1 SMP Wed Mar 18 05:58:51 UTC 2015" HostName=arm04-builder23.arm.fedoraproject.org Architecture=armv7l)
  Socket L#0 (P#9 CPUModel="ARMv7 Processor rev 0 (v7l)" CPUImplementer=0x41 CPUArchitecture=7 CPUVariant=0x3 CPUPart=0xc09 CPURevision=0)
    Core L#0 (P#0)
      PU L#0 (P#0)
    Core L#1 (P#1)
      PU L#1 (P#1)
    Core L#2 (P#2)
      PU L#2 (P#2)
    Core L#3 (P#3)
      PU L#3 (P#3)
depth 0:	1 Machine (type #1)
 depth 1:	1 Socket (type #3)
  depth 2:	4 Core (type #5)
   depth 3:	4 PU (type #6)
4 processors not represented in topology: 0x0000000f,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0x0
~~~~~

xml

~~~~~
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc.dtd">
<topology>
  <object type="Machine" os_index="0" cpuset="0x0000000f" complete_cpuset="0x0000000f,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0x0000000f" online_cpuset="0x0000000f,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0x0000000f" allowed_cpuset="0x0000000f,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0x0000000f" local_memory="4236419072">
    <page_type size="4096" count="1034282"/>
    <info name="HardwareName" value="Highbank"/>
    <info name="HardwareRevision" value="0000"/>
    <info name="HardwareSerial" value="0000000000000000"/>
    <info name="Backend" value="Linux"/>
    <info name="OSName" value="Linux"/>
    <info name="OSRelease" value="3.19.1-201.fc21.armv7hl"/>
    <info name="OSVersion" value="#1 SMP Wed Mar 18 05:58:51 UTC 2015"/>
    <info name="HostName" value="arm04-builder23.arm.fedoraproject.org"/>
    <info name="Architecture" value="armv7l"/>
    <object type="Socket" os_index="9" cpuset="0x0000000f" complete_cpuset="0x0000000f" online_cpuset="0x0000000f" allowed_cpuset="0x0000000f">
      <info name="CPUModel" value="ARMv7 Processor rev 0 (v7l)"/>
      <info name="CPUImplementer" value="0x41"/>
      <info name="CPUArchitecture" value="7"/>
      <info name="CPUVariant" value="0x3"/>
      <info name="CPUPart" value="0xc09"/>
      <info name="CPURevision" value="0"/>
      <object type="Core" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" online_cpuset="0x00000001" allowed_cpuset="0x00000001">
        <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" online_cpuset="0x00000001" allowed_cpuset="0x00000001"/>
      </object>
      <object type="Core" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" online_cpuset="0x00000002" allowed_cpuset="0x00000002">
        <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" online_cpuset="0x00000002" allowed_cpuset="0x00000002"/>
      </object>
      <object type="Core" os_index="2" cpuset="0x00000004" complete_cpuset="0x00000004" online_cpuset="0x00000004" allowed_cpuset="0x00000004">
        <object type="PU" os_index="2" cpuset="0x00000004" complete_cpuset="0x00000004" online_cpuset="0x00000004" allowed_cpuset="0x00000004"/>
      </object>
      <object type="Core" os_index="3" cpuset="0x00000008" complete_cpuset="0x00000008" online_cpuset="0x00000008" allowed_cpuset="0x00000008">
        <object type="PU" os_index="3" cpuset="0x00000008" complete_cpuset="0x00000008" online_cpuset="0x00000008" allowed_cpuset="0x00000008"/>
      </object>
    </object>
  </object>
</topology>
~~~~~

I did export HWLOC_DEBUG_CHECK=1 before this, but not sure it generated any output (stdout/stderr)

**Comment by opoplawski** [comment]
I could probably finagle a gdb backtrace if you could point me to what to look for.

**Comment by rhc54** [comment]
Mostly want to see where in the OMPI library we segfault. So a gdb off of the corefile, assuming you can generate it, would be helpful.

**Comment by bgoglin** [comment]
Ok there's something strange in
```
complete_cpuset="0x0000000f,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0x0000000f"
```
Looks like somebody reports a very high processor index somewhere.
Is this a big.little processor? The other 4 cores may have number 233{6,7,8,9} then.

Can you check that /sys/devices/system/cpu/ only contains cpu{0,1,2,3} and nothing else?

If not, can you check if /sys/devices/system/cpu/cpu*/topology/*_siblings_list contains any big numbers (not only 0-3) ?

Thanks

**Comment by opoplawski** [comment]
ls /sys/devices/system/cpu/
cpu0
cpu1
cpu2
cpu3
cpuidle
kernel_max
offline
online
possible
power
present
uevent

 cat /sys/devices/system/cpu/cpu0/topology/core_siblings_list /sys/devices/system/cpu/cpu0/topology/thread_siblings_list /sys/devices/system/cpu/cpu1/topology/core_siblings_list /sys/devices/system/cpu/cpu1/topology/thread_siblings_list /sys/devices/system/cpu/cpu2/topology/core_siblings_list /sys/devices/system/cpu/cpu2/topology/thread_siblings_list /sys/devices/system/cpu/cpu3/topology/core_siblings_list /sys/devices/system/cpu/cpu3/topology/thread_siblings_list
0-3
0
0-3
1
0-3
2
0-3
3

**Comment by opoplawski** [comment]
I finally have access to a builder machine.  However I'm now being thwarted by the fact the gdb in broken on arm in Fedora Rawhide - https://bugzilla.redhat.com/show_bug.cgi?id=1196181  The fates continue to conspire against me.

**Comment by bgoglin** [comment]
Can you do hwloc-gather-topology?

**Comment by opoplawski** [comment]
Yes.  http://www.cora.nwra.com/~orion/armbuilder.tar.bz2

**Comment by bgoglin** [comment]
Ah, looks like it's the first time hwloc runs on arm with /proc/device-tree enabled, and there are some unexpected changes with respect to /proc/device-tree on power processors (arm device-tree returns strange processor numbers instead of 0-3). So hwloc root {online,allowed,complete}_cpuset are buggy.

Can you modify opal/mca/hwloc/hwloc191/hwloc/src/topology.c, and comment out every place where look_powerpc_device_tree() is called ?

Thanks!

**Comment by opoplawski** [comment]
Good catch.  Yes, commenting those calls out allows the tests to succeed.  So, I suppose we can close this and file a bug on hwloc?

**Comment by rhc54** [comment]
Thanks guys!! I'd say leave this open until we bring the patch across so we don't forget.

**Comment by bgoglin** [comment]
Here's the hwloc v1.9 commit that OMPI should take: https://github.com/open-mpi/hwloc/commit/f714f8d634397436c14c529d462a5cb277b8d08f

**Comment by rhc54** [comment]
Thanks! Got it.
