### ISSUE TITLE
Improve CUDA extension code

### ISSUE THREAD

**Issue by rolfv** [open-mpi/ompi-release#418]
Need to make at least two more changes to the extension code.
1. Have them built unconditionally so they are always available.
2. Have them then properly set the MPIX_CUDA_AWARE_MACRO to 0 or 1 depending on whether library has CUDA-aware configured in.  Also have the MPIX_Query_cuda_support() function do the right thing.  

The problem is now they are only set when we have CUDA-aware so to use them requires a bunch of ifdefs.

**Comment by rolfv** [comment]
bot:milestone:v2.0.0
bot:label:bug
bot:assign: @rolfv

**Comment by jsquyres** [comment]
Depending on how long you want this issue open, you might want to move it to the ompi repo (per https://github.com/open-mpi/ompi/wiki/SubmittingBugs).

**Comment by rolfv** [comment]
Closing this issue and opening in the the ompi repository.
