### ISSUE TITLE
Openmpi / mpiexec does not obey SIGTSTP (signal 20)

### ISSUE THREAD

**Issue by kaiserkarl13** [open-mpi/ompi-release#531]
If I run a job with mpiexec, then press CTRL-Z (or send the signal some other way, such as through top, kill, or htop), it prints
  mpiexec: Forwarding signal 20 to job
and then waits instead of suspending itself.

Expected behavior:  SIGTSTP is caught by mpiexec, transmitted to each "child" process, then processed normally (i.e., mpiexec itself stops).

Actual behavior:  SIGTSTP is caught by mpiexec, converted into SIGSTOP and sent to each child process, then continues (thereby locking up the terminal if it is still attached to one rather than stopping and thereby giving control back to the user).

I'm not 100% certain about the converting to SIGSTOP part, but I was reading somewhere that it does that---this seems incorrect behavior, as SIGTSTP can be caught, but SIGSTOP cannot, but for most use cases I can think of it wouldn't matter.  However, the part about not re-raising the signal again is a bug.

I can confirm that this did what I expect it to do for OpenMPI 1.4.3 and 1.6.3.  The Fedora builds of OpenMPI 1.7.x and 1.8.x cause trouble, though, as does my own build of 1.8.6.

This was originally submitted as a bug report at Bugzilla, https://bugzilla.redhat.com/show_bug.cgi?id=1151657

**Comment by jsquyres** [comment]
Sorry, we missed this bug because we only file bugs on the main OMPI repo -- this ompi-release repo is just for pull requests to go to the release branches.

Can you re-file this over on the main ompi repo?  Thanks!
