### ISSUE TITLE
The v1.10.0 release package can't build on Power8 LE

### ISSUE THREAD

**Issue by Zhiming-Wang** [open-mpi/ompi-release#596]
I downloaded the v1.10.0 release package from http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.0.tar.gz and built it by xlc.
The building was failed on RHEL 7.1 Power8 LE.
The steps:
$ ./configure --prefix=/home/wangzm/ompi-110rel-xlc-opt-p8le ... && make all install
...
make[2]: Entering directory `/tmp/tmp-dir/openmpi-1.10.0/ompi/mpi/fortran/use-mpi-ignore-tkr'
  FCLD     libmpi_usempi_ignore_tkr.la
/lib64/librt.so: could not read symbols: File in wrong format
make[2]: *** [libmpi_usempi_ignore_tkr.la] Error 1
make[2]: Leaving directory `/tmp/tmp-dir/openmpi-1.10.0/ompi/mpi/fortran/use-mpi-ignore-tkr'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/tmp-dir/openmpi-1.10.0/ompi'
make: *** [all-recursive] Error 1
$ cd /tmp/tmp-dir/openmpi-1.10.0/ompi/mpi/fortran/use-mpi-ignore-tkr
$ make -n
echo "  FCLD    " libmpi_usempi_ignore_tkr.la;/bin/sh ../../../../libtool --silent --tag=FC   --mode=link xlf -I../../../../ompi/include -I../../../../ompi/include -I../../../.. -I../../../..  -q64 -qarch=pwr8 -qtune=pwr8 -O3 -qxflag=nseq -version-info 6:0:0   -o libmpi_usempi_ignore_tkr.la -rpath /usr/local/lib mpi-ignore-tkr.lo mpi-ignore-tkr-sizeof.lo  -lrt -lutil
$ /bin/sh -x ../../../../libtool --silent --tag=FC --mode=link xlf -I../../../../ompi/include -I../../../../ompi/include -I../../../.. -I../../../.. -q64 -qarch=pwr8 -qtune=pwr8 -O3 -qxflag=nseq -version-info 6:0:0 -o libmpi_usempi_ignore_tkr.la -rpath /usr/local/lib mpi-ignore-tkr.lo mpi-ignore-tkr-sizeof.lo -lrt -lutil
...
++ cmd='/usr/bin/ld -m elf64ppc -shared  .libs/mpi-ignore-tkr.o .libs/mpi-ignore-tkr-sizeof.o   -lrt -lutil  -soname libmpi_usempi_ignore_tkr.so.6 -o .libs/libmpi_usempi_ignore_tkr.so.6.0.0'
+ :
+ false
+ eval '/usr/bin/ld -m elf64ppc -shared  .libs/mpi-ignore-tkr.o .libs/mpi-ignore-tkr-sizeof.o   -lrt -lutil  -soname libmpi_usempi_ignore_tkr.so.6 -o .libs/libmpi_usempi_ignore_tkr.so.6.0.0'
++ /usr/bin/ld -m elf64ppc -shared .libs/mpi-ignore-tkr.o .libs/mpi-ignore-tkr-sizeof.o -lrt -lutil -soname libmpi_usempi_ignore_tkr.so.6 -o .libs/libmpi_usempi_ignore_tkr.so.6.0.0
/lib64/librt.so: could not read symbols: File in wrong format
+ lt_exit=1
+ test link = relink
+ exit 1

As shown above, the "elf64ppc" option was used for "/usr/bin/ld". At Power8 LE, the "elf64lppc" should be used. I reran "./autogen.pl" at Power8 LE, the building was passed. 
I don't know how was "configure" file generated at release package. I think the Power BE and LE are not distinguished somewhere, so the "elf64ppc" option for Power BE is misapplied on Power LE platform.

**Comment by Zhiming-Wang** [comment]
bot:milestone:v1.10.0
bot:label:bug
bot:assign: @jsquyres

**Comment by Zhiming-Wang** [comment]
@jsquyres  I can't see my name on the webpage. How to add myself at http://github.com/orgs/open-mpi/people?

**Comment by rhc54** [comment]
@Zhiming-Wang Please don't open issues against the release repo - nobody will see them. They should be opened against the master repo, and labeled there for v1.10.

**Comment by Zhiming-Wang** [comment]
Thanks @rhc54  I create another one at master repo. 
https://github.com/open-mpi/ompi/issues/922

**Comment by jsquyres** [comment]
@Zhiming-Wang Just to follow up -- your name was on the IBM schedule A, so I just added you to the Open MPI Github Organization (I think you have to click through the invitation email that you probably just received).
