### ISSUE TITLE
v2.x branch fails to build with released plfs available

### ISSUE THREAD

**Issue by loveshack** [open-mpi/ompi-release#880]
The build will fail if you have the released version (2.5) of plfs installed because the signature of plfs_setxattr used by OMPI's fs component was changed after the release.  I think configure should check for the correct signature of plfs_setxattr.

**Comment by hppritcha** [comment]
@loveshack I assume this is also showing on master.  Actually for the Open MPI project, we open issues on open-mpi/ompi rather than ompi-release. Closing this issue.  I opened open-mpi/ompi#1271 to track this probem
